# src/codec/packets/configuration/clientbound/keep_alive.py

from codec.packets.packet import Packet
from codec.data_types.primitives.long import Long
from codec.data_types.primitives.varint import VarInt


class KeepAlive(Packet):
    """
    Configuration Keep Alive packet.

    Packet ID:
        0x04
    State:
        Configuration
    Bound:
        Clientbound

    Fields:
        keep_alive_id (Long): Random keep-alive identifier generated by the server.
    """

    __slots__ = ("keep_alive_id",)

    def __init__(self, data: bytes) -> None:
        super().__init__(packet_id=VarInt(0x04))

        self.keep_alive_id, consumed = Long.from_bytes(data)
        if consumed != len(data):
            raise ValueError(
                f"KeepAlive has unexpected trailing bytes: {len(data) - consumed}"
            )

    def _iter_fields(self):
        yield self.keep_alive_id
