# src/codec/packets/login/clientbound/custom_query.py

from codec.packets.packet import Packet
from codec.data_types.primitives.varint import VarInt
from codec.data_types.complex.identifier import Identifier


class CustomQuery(Packet):
    """Login Custom Query packet.

    Packet ID:
        0x04
    State:
        Login
    Bound:
        Clientbound

    Fields:
        message_id (VarInt): Unique ID generated by the server
        channel (Identifier): Name of the plugin channel
        data (bytes): Optional payload, format depends on the channel
                      Max 1048576 bytes if channel unrecognized by vanilla client
    """

    __slots__ = ("message_id", "channel", "data")

    def __init__(self, data: bytes) -> None:
        super().__init__(packet_id=VarInt(0x04))
        offset = 0

        # Parse message_id
        self.message_id, consumed = VarInt.from_bytes(data[offset:])
        offset += consumed

        # Parse channel
        self.channel, consumed = Identifier.from_bytes(data[offset:])
        offset += consumed

        # The rest is data (may be empty)
        self.data = data[offset:]
        if len(self.data) > 1048576:
            raise ValueError(
                f"CustomQuery data too long: {len(self.data)} bytes " "(max 1048576)"
            )

    def _iter_fields(self):
        yield self.message_id
        yield self.channel
        yield self.data
